version: '3.3' 
services: 
  app:
      dockerfile: Dockerfile
      environment:
         SPRING_PROFILES_ACTIVE: dev
         CURSOMC_DB_POSTGRESQL: postgres
         CURSOMC_DB_PORT: 5432
         CURSOMC_DB_DATABASE: curso_spring
         CURSOMC_DB_USERNAME: postgres
         CURSOMC_DB_PASSWORD: admin
      image: cursomc
      ports:
         -8080:8080
      depends_on:
         - postgres
      links:
         - postgres:postgres
postgres:
        image: postgres
        environment:
          POSTGRES_DB: curso_spring
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
pgadmin:
       image: dpage/pgadmin4
       environment:
         PGADMIN_DEFAULT_EMAIL: "robert.suporteweb@gmail.com"
         PGADMIN_DEFAULT_PASSWORD: "admin"
       ports:
         - "16543:80"
       depends_on:
         - postgress